name: tp_devops

on: push

jobs:
  ci:
    runs-on : ubuntu-latest
    services:
      postgres: 
        image: postgres:latest
        env:
          POSTGRES_DB: tp_devops
          POSTGRES_USER: tp_devops
          POSTGRES_PASSWORD: tp_devops
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8.0
      - run : ./gradlew assemble
      - run : ./gradlew check -i -P dababase.url=postgres/tp_devops
     

