name: tp_devops

on: push

jobs:
  ci:
    steps:
      -run : ./gradlew assemble
      -run : ./gradlew check
      -run : ./gradlew dockerBuildImage
      -run : docker-compose up
      -run : docker push felixpotie/tp_devops
