name: tp_devops

on: push

jobs:
  ci:
    runs-on : ubuntu-latest
    container: openjdk:8-jdk
    services:
      postgres: 
        image: postgres:latest
        env:
          POSTGRES_DB: tp_devops
          POSTGRES_USER: tp_devops
          POSTGRES_PASSWORD: tp_devops
    steps:
      - uses: actions/checkout@v2
      - run : ./gradlew assemble
      - run : ./gradlew check -i -P database.url=postgres/tp_devops
      - run : ./gradlew dockerBuildImage
  ci_docker:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run : ./gradlew dockerBuildImage
      - run : docker push felixpotie/tp_devops:latest